services:
    mongodb:
        extends:
            service: mongodb-service
            file: mongodb/docker-services.yml
        env_file:
            - .env
        networks:
            - app
            - satoru-app

    discord-js-app:
        extends:
            service: discord-js-service
            file: discord-bot/docker-services.yml
        env_file:
            - .env
        environment:
            MONGO_USERNAME: ${MONGO_USERNAME:-admin}
            MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
            MONGO_HOSTNAME: mongodb
            MONGO_PORT: ${MONGO_PORT:-27017}
            MONGO_DB: ${MONGO_DB:-satoro_bot}
            NODE_DOCKER_ENV: ${NODE_DOCKER_ENV:-20}
            DOTA_API_PORT: ${DOTA_API_PORT:-open-dota}
            STRATZ_DOTA_API_TOKEN: ${STRATZ_DOTA_API_TOKEN}
            STRATZ_API_URL: ${STRATZ_API_URL:-https://api.stratz.com/graphql}
            STRATZ_API_TYPE: ${STRATZ_API_TYPE:-graphiql}
        stop_grace_period: 40s
        networks:
            - app
            - satoru-app
        depends_on:
            - mongodb

    api-app:
        extends:
            service: api-service
            file: api/docker-services.yml
        env_file:
            - .env
        environment:
            MONGO_USERNAME: ${MONGO_USERNAME:-admin}
            MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
            MONGO_HOSTNAME: mongodb
            MONGO_PORT: ${MONGO_PORT:-27017}
            MONGO_DB: ${MONGO_DB:-satoro_bot}
            NODE_DOCKER_ENV: ${NODE_DOCKER_ENV:-20}
            REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
            REDIS_PORT: ${REDIS_PORT:-6379}
        stop_grace_period: 1m
        networks:
            - app
        depends_on:
            - mongodb
            - redis

    redis:
        image: redis
        container_name: redis
        ports:
            - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
        restart: always
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
            REDIS_PORT: ${REDIS_PORT:-6379}
        env_file:
            - .env
        networks:
            - app

networks:
    app:
        driver: bridge
    satoru-app:
        external: true
        driver: bridge

volumes:
    mongodb_data:
        driver: local
