services:
  discord-js-service:
    image: node:20-alpine
    container_name: satoru-discord-bot
    working_dir: ${DOCKER_PROJECT_DIR:-/usr/app}
    restart: unless-stopped
    environment:
      ENV: ${NODE_ENV:-dev}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      GUILD_ID: ${GUILD_ID:-}
      NODE_DOCKER_ENV: ${NODE_DOCKER_ENV:-20}
      DOCKER_PROJECT_DIR: ${DOCKER_PROJECT_DIR:-/usr/app}
      EXPRESS_PORT: ${EXPRESS_PORT:-3000}
    volumes:
      - ./:${DOCKER_PROJECT_DIR:-/usr/app}
      - ./node_modules:${DOCKER_PROJECT_DIR:-/usr/app}/node_modules
    ports:
      - ${NODE_PORT:-80}:8080
    command: npm run ${NODE_ENV:-dev}