export enum RanksEnum {
    "Calibration" = 0,
    "Herald I" = 11,
    "Herald II",
    "Herald III",
    "Herald IV",
    "Herald V",
    "Guardian I" = 21,
    "Guardian II",
    "Guardian III",
    "Guardian IV",
    "Guardian V",
    "Crusader I" = 31,
    "Crusader II",
    "Crusader III",
    "Crusader IV",
    "Crusader V",
    "Archon I" = 41,
    "Archon II",
    "Archon III",
    "Archon IV",
    "Archon V",
    "Legend I" = 51,
    "Legend II",
    "Legend III",
    "Legend IV",
    "Legend V",
    "Ancient I" = 61,
    "Ancient II",
    "Ancient III",
    "Ancient IV",
    "Ancient V",
    "Divine I" = 71,
    "Divine II",
    "Divine III",
    "Divine IV",
    "Divine V",
    "Immortal" = 80,
}

export type RanksT = keyof typeof RanksEnum